# Generated by Django 4.2.7 on 2023-11-30 15:59

import books.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication_year',
            field=models.PositiveSmallIntegerField(validators=[books.validators.validate_year], verbose_name='Год издания'),
        ),
    ]
